### ISSUE TITLE
missing `ruamel-yaml` dependency

### ISSUE THREAD

**Issue by knoopx** [bachya/linkding-cli#373]
project is missing `ruamel-yaml` as dependency, had to install it manually:

```
pipx install linkding-cli
  installed package linkding-cli 2023.12.0, installed using Python 3.12.4
  These apps are now globally available
    - linkding
done! ✨ 🌟 ✨
knoopx@desktop ~/D/linkding> linkding bookmarks
Traceback (most recent call last):
  File "/home/knoopx/.local/bin/linkding", line 5, in <module>
    from linkding_cli.cli import APP
  File "/home/knoopx/.local/pipx/venvs/linkding-cli/lib/python3.12/site-packages/linkding_cli/cli.py", line 13, in <module>
    from linkding_cli.core import LinkDing
  File "/home/knoopx/.local/pipx/venvs/linkding-cli/lib/python3.12/site-packages/linkding_cli/core.py", line 9, in <module>
    from linkding_cli.config import Config
  File "/home/knoopx/.local/pipx/venvs/linkding-cli/lib/python3.12/site-packages/linkding_cli/config.py", line 7, in <module>
    from ruamel.yaml import YAML
ModuleNotFoundError: No module named 'ruamel'
```

**Comment by bachya** [comment]
I missed this because the local dev environment created by `script/setup` _does_ have `ruamel-yaml` installed, but only because `pre-commit` (a dev dependency) requires it. I'll ensure it's added to the production manifest.
