### ISSUE TITLE
Ruamel module not included

### ISSUE THREAD

**Issue by mischavandenburg** [bachya/linkding-cli#404]
Tested on Arch Linux and MacOS

`pipx install linkding-cli`

`linkding`

```
linkding
Traceback (most recent call last):
  File "/Users/mischa/.local/bin/linkding", line 5, in <module>
    from linkding_cli.cli import APP
  File "/Users/mischa/.local/pipx/venvs/linkding-cli/lib/python3.12/site-packages/linkding_cli/cli.py", line 14, in <module>
    from linkding_cli.core import LinkDing
  File "/Users/mischa/.local/pipx/venvs/linkding-cli/lib/python3.12/site-packages/linkding_cli/core.py", line 10, in <module>
    from linkding_cli.config import Config
  File "/Users/mischa/.local/pipx/venvs/linkding-cli/lib/python3.12/site-packages/linkding_cli/config.py", line 8, in <module>
    from ruamel.yaml import YAML
ModuleNotFoundError: No module named 'ruamel'
```

I saw you did a PR to include it in the pyproject.toml, but maybe that wasn't built?

**Comment by bachya** [comment]
Just released [2024.09.0](https://github.com/bachya/linkding-cli/releases/tag/2024.09.0) with a fix for this.
